### ISSUE TITLE
currently the widget is always opening on a modal, is it possible to open in a custom location in a different div?

### ISSUE THREAD

**Issue by arunicus** [puranjayjain/md-date-time-picker#222]
currently the widget is always opening on a modal, is it possible to open in a custom location in a different div?

**Comment by puranjayjain** [comment]
Not through configuration. Since it was always the intention of the project to open in a modal similar to material design specification for the picker. However, if you want you can start your own fork with the widget opening in a custom location. I am closing this issue, as I feel this should answer your question. You can reopen or open another one if you have more questions.
