### ISSUE TITLE
Missing colon between hour and minute in 24-hour format

### ISSUE THREAD

**Issue by db-dblank** [puranjayjain/md-date-time-picker#56]
![missing-colon](https://cloud.githubusercontent.com/assets/15021504/15504310/c27f0a0c-2194-11e6-8add-a534d5f13614.png)

**Comment by puranjayjain** [comment]
@db-dblank it is deliberately not being put there since in 24 hour modes you don't essentially put a colon between the values e.g 2400 hours or 1200 hours etc. Similar to the military way of putting the time. 

Also, to differentiate between the 24 hour mode and the 12 hour mode.Also, the material design spec is not very clear on this matter.
Although I might implement this if you can provide me with a strong reference.

**Comment by db-dblank** [comment]
Hi @puranjayjain,

All my apps on Android has the colon between hour and minute, see the Google Calendar app:

![calendar-timepicker](https://cloud.githubusercontent.com/assets/15021504/15508046/5a7d73a2-21a4-11e6-921b-cea2f03e8724.jpg)

Or, add an argument to show or hide de colon.

Thanks.

**Comment by puranjayjain** [comment]
@db-dblank I'll add the option for it to be configurable that doesn't hurt anybody :smile:

**Comment by puranjayjain** [comment]
Contradicting to my original statement.This option should indeed be default and not opt-in and hence colon should be true by default. (removal is not an option until v3.0.0 since this can have breaking changes). 

https://www.google.com/design/spec/patterns/data-formats.html#data-formats-date-time
